### ISSUE TITLE
Other implementations based on Javascript？

### ISSUE THREAD

**Issue by zzq0324** [EmilDohne/psd_tools_apply_warp#1]
Thank you for your share, great work!

Do you have other implementations based on browser JavaScript(webgl)?

**Comment by EmilDohne** [comment]
Hi @zzq0324, this implementation is just a copy of what I've already implemented on the CPP side for the PhotoshopAPI. Likely once that is done this repository will get deleted. As for javascript I don't have much experience with it so you'd have to port it yourself
